### ISSUE TITLE
Rails 5.2.1中加入role_core后db:migrate报错

### ISSUE THREAD

**Issue by hjleochen** [rails-engine/role_core#5]
Rails 5.2.1
ruby 2.3.6p384

重现步骤:
rails new TestApp
rails g scaffold posts title:string

rake db:migrate是成功的.
Gemfile加入 role_core
rake db:migrate

```
rake aborted!
NoMethodError: undefined method `force_equality?' for #<ActiveModel::Type::String:0x00005595c4650018>
/home/leo/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activerecord-5.2.1/lib/active_record/relation/predicate_builder.rb:55:in `build'
/home/leo/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activerecord-5.2.1/lib/active_record/relation/predicate_builder.rb:111:in `block in expand_from_hash'
```

**Comment by jasl** [comment]
我周日会看看

**Comment by jasl** [comment]
感谢发现问题，暴露了我兼容 Rails 4 的姿势不对，直接更新一下版本就好了
